import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';
import './ui/globals.css';
import { Suspense } from 'react';
import LoadingData from './ui/LoadingData';

const mulish = Mulish({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Suspense fallback={<LoadingData></LoadingData>}>{children}</Suspense>
        <footer>Bitnovo</footer>
      </body>
    </html>
  );
}
